name: WorldGuardExtraFlags
version: 4.1.1
description: Adds more flags to WorldGuard to help manage your server easily!
author: isokissa3
website: https://goldtreevers.net
depend: [ WorldGuard ]
softdepend: [ MythicMobs, FastAsyncWorldEdit, Essentials ]

main: net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin