name: WorldGuardExtraFlags
description: Adds more flags to WorldGuard to help manage your server easily!

version: 4.1.5-SNAPSHOT
api-version: 1.13

author: isokissa3
website: https://goldtreevers.net

depend: [ WorldGuard ]
softdepend: [ Essentials, ProtocolLib ]

main: net.goldtreeservers.worldguardextraflags.WorldGuardExtraFlagsPlugin